-- MySQL RegionStore Complete Implementation (v1-67)
-- This migration creates all OpenSim master RegionStore tables with full v67 compatibility

-- OpenSim Master: Regions table with hybrid compatibility
CREATE TABLE `regions` (
    `uuid` VARCHAR(36) NOT NULL PRIMARY KEY,
    `regionHandle` BIGINT UNSIGNED NOT NULL,
    `regionName` VARCHAR(128) DEFAULT NULL,
    `regionRecvKey` VARCHAR(128) DEFAULT NULL,
    `regionSendKey` VARCHAR(128) DEFAULT NULL,
    `regionSecret` VARCHAR(128) DEFAULT NULL,
    `regionDataURI` VARCHAR(255) DEFAULT NULL,
    `serverIP` VARCHAR(64) DEFAULT NULL,
    `serverPort` INT UNSIGNED DEFAULT NULL,
    `serverURI` VARCHAR(255) DEFAULT NULL,
    `locX` INT UNSIGNED DEFAULT NULL,
    `locY` INT UNSIGNED DEFAULT NULL,
    `locZ` INT UNSIGNED DEFAULT NULL,
    `eastOverrideHandle` BIGINT UNSIGNED DEFAULT NULL,
    `westOverrideHandle` BIGINT UNSIGNED DEFAULT NULL,
    `southOverrideHandle` BIGINT UNSIGNED DEFAULT NULL,
    `northOverrideHandle` BIGINT UNSIGNED DEFAULT NULL,
    `regionAssetURI` VARCHAR(255) DEFAULT NULL,
    `regionAssetRecvKey` VARCHAR(128) DEFAULT NULL,
    `regionAssetSendKey` VARCHAR(128) DEFAULT NULL,
    `regionUserURI` VARCHAR(255) DEFAULT NULL,
    `regionUserRecvKey` VARCHAR(128) DEFAULT NULL,
    `regionUserSendKey` VARCHAR(128) DEFAULT NULL,
    `regionMapTexture` CHAR(36) DEFAULT NULL,
    `serverHttpPort` INT DEFAULT NULL,
    `serverRemotingPort` INT DEFAULT NULL,
    `owner_uuid` CHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
    `originUUID` CHAR(36) DEFAULT NULL,
    `access` INT UNSIGNED DEFAULT 1,
    `ScopeID` CHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
    `sizeX` INT NOT NULL DEFAULT 0,
    `sizeY` INT NOT NULL DEFAULT 0,
    `flags` INT NOT NULL DEFAULT 0,
    `last_seen` INT NOT NULL DEFAULT 0,
    `PrincipalID` CHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
    `Token` VARCHAR(255) NOT NULL DEFAULT '',
    `parcelMapTexture` VARCHAR(36) DEFAULT NULL,
    KEY `regionName` (`regionName`),
    KEY `regionHandle` (`regionHandle`),
    KEY `overrideHandles` (`eastOverrideHandle`,`westOverrideHandle`,`southOverrideHandle`,`northOverrideHandle`),
    KEY `ScopeID` (`ScopeID`),
    KEY `flags` (`flags`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- OpenSim Master: Prims table with all v67 features
CREATE TABLE `prims` (
    `CreationDate` INT DEFAULT NULL,
    `Name` VARCHAR(255) DEFAULT NULL,
    `Text` VARCHAR(255) DEFAULT NULL,
    `Description` VARCHAR(255) DEFAULT NULL,
    `SitName` VARCHAR(255) DEFAULT NULL,
    `TouchName` VARCHAR(255) DEFAULT NULL,
    `ObjectFlags` INT DEFAULT NULL,
    `OwnerMask` INT DEFAULT NULL,
    `NextOwnerMask` INT DEFAULT NULL,
    `GroupMask` INT DEFAULT NULL,
    `EveryoneMask` INT DEFAULT NULL,
    `BaseMask` INT DEFAULT NULL,
    `PositionX` FLOAT DEFAULT NULL,
    `PositionY` FLOAT DEFAULT NULL,
    `PositionZ` FLOAT DEFAULT NULL,
    `GroupPositionX` FLOAT DEFAULT NULL,
    `GroupPositionY` FLOAT DEFAULT NULL,
    `GroupPositionZ` FLOAT DEFAULT NULL,
    `VelocityX` FLOAT DEFAULT NULL,
    `VelocityY` FLOAT DEFAULT NULL,
    `VelocityZ` FLOAT DEFAULT NULL,
    `AngularVelocityX` FLOAT DEFAULT NULL,
    `AngularVelocityY` FLOAT DEFAULT NULL,
    `AngularVelocityZ` FLOAT DEFAULT NULL,
    `AccelerationX` FLOAT DEFAULT NULL,
    `AccelerationY` FLOAT DEFAULT NULL,
    `AccelerationZ` FLOAT DEFAULT NULL,
    `RotationX` FLOAT DEFAULT NULL,
    `RotationY` FLOAT DEFAULT NULL,
    `RotationZ` FLOAT DEFAULT NULL,
    `RotationW` FLOAT DEFAULT NULL,
    `SitTargetOffsetX` FLOAT DEFAULT NULL,
    `SitTargetOffsetY` FLOAT DEFAULT NULL,
    `SitTargetOffsetZ` FLOAT DEFAULT NULL,
    `SitTargetOrientW` FLOAT DEFAULT NULL,
    `SitTargetOrientX` FLOAT DEFAULT NULL,
    `SitTargetOrientY` FLOAT DEFAULT NULL,
    `SitTargetOrientZ` FLOAT DEFAULT NULL,
    `UUID` CHAR(36) NOT NULL DEFAULT '' PRIMARY KEY,
    `RegionUUID` CHAR(36) DEFAULT NULL,
    `CreatorID` VARCHAR(255) NOT NULL DEFAULT '',
    `OwnerID` CHAR(36) DEFAULT NULL,
    `GroupID` CHAR(36) DEFAULT NULL,
    `LastOwnerID` CHAR(36) DEFAULT NULL,
    `SceneGroupID` CHAR(36) DEFAULT NULL,
    `LinkNumber` INT DEFAULT NULL,
    `Material` TINYINT DEFAULT NULL,
    -- v52+ features
    `PassCollisions` TINYINT(4) NOT NULL DEFAULT 0,
    `Vehicle` TEXT DEFAULT NULL,
    -- v53+ features  
    `RotationAxisLocks` TINYINT(4) NOT NULL DEFAULT 0,
    -- v56+ features
    `RezzerID` CHAR(36) DEFAULT NULL,
    -- v57+ features
    `PhysInertia` TEXT DEFAULT NULL,
    -- v58+ features
    `sopanims` BLOB DEFAULT NULL,
    -- v59+ features
    `standtargetx` FLOAT DEFAULT 0.0,
    `standtargety` FLOAT DEFAULT 0.0,
    `standtargetz` FLOAT DEFAULT 0.0,
    `sitactrange` FLOAT DEFAULT 0.0,
    -- v61+ features
    `pseudocrc` INT DEFAULT 0,
    -- v65+ features
    `lnkstBinData` BLOB DEFAULT NULL,
    -- v67+ features
    `StartStr` TEXT DEFAULT NULL,
    KEY `prims_regionuuid` (`RegionUUID`),
    KEY `prims_parentid` (`SceneGroupID`),
    KEY `prims_ownerid` (`OwnerID`),
    KEY `prims_creatorid` (`CreatorID`),
    KEY `prims_groupid` (`GroupID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;