-- MySQL RegionStore Advanced Features Implementation
-- This migration creates advanced RegionStore tables with MySQL optimizations

-- RegionStore: Region Settings
CREATE TABLE `regionsettings` (
    `regionUUID` CHAR(36) NOT NULL PRIMARY KEY,
    `block_terraform` TINYINT(4) NOT NULL DEFAULT 1,
    `block_fly` TINYINT(4) NOT NULL DEFAULT 0,
    `allow_damage` TINYINT(4) NOT NULL DEFAULT 0,
    `restrict_pushing` TINYINT(4) NOT NULL DEFAULT 0,
    `allow_land_resell` TINYINT(4) NOT NULL DEFAULT 1,
    `allow_land_join_divide` TINYINT(4) NOT NULL DEFAULT 1,
    `block_show_in_search` TINYINT(4) NOT NULL DEFAULT 0,
    `agent_limit` INT NOT NULL DEFAULT 10,
    `object_bonus` DOUBLE NOT NULL DEFAULT 1.0,
    `maturity` TINYINT NOT NULL DEFAULT 1,
    `disable_scripts` TINYINT(4) NOT NULL DEFAULT 0,
    `disable_collisions` TINYINT(4) NOT NULL DEFAULT 0,
    `disable_physics` TINYINT(4) NOT NULL DEFAULT 0,
    `terrain_texture_1` CHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
    `terrain_texture_2` CHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
    `terrain_texture_3` CHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
    `terrain_texture_4` CHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
    `elevation_1_nw` DOUBLE NOT NULL DEFAULT 10.0,
    `elevation_2_ne` DOUBLE NOT NULL DEFAULT 10.0,
    `elevation_1_se` DOUBLE NOT NULL DEFAULT 10.0,
    `elevation_2_sw` DOUBLE NOT NULL DEFAULT 10.0,
    `water_height` DOUBLE NOT NULL DEFAULT 20.0,
    `terrain_raise_limit` DOUBLE NOT NULL DEFAULT 100.0,
    `terrain_lower_limit` DOUBLE NOT NULL DEFAULT -100.0,
    `use_estate_sun` TINYINT(4) NOT NULL DEFAULT 1,
    `fixed_sun` TINYINT(4) NOT NULL DEFAULT 0,
    `sun_position` DOUBLE NOT NULL DEFAULT 0.0,
    `covenant` CHAR(36) DEFAULT NULL,
    `covenant_datetime` INT NOT NULL DEFAULT 0,
    `Sandbox` TINYINT(4) NOT NULL DEFAULT 0,
    `sunvectorx` DOUBLE NOT NULL DEFAULT 0.0,
    `sunvectory` DOUBLE NOT NULL DEFAULT 0.0,
    `sunvectorz` DOUBLE NOT NULL DEFAULT 0.0,
    `loaded_creation_datetime` INT NOT NULL DEFAULT 0,
    `loaded_creation_id` VARCHAR(64) NOT NULL DEFAULT '',
    `map_tile_ID` CHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
    `minimum_age` INT NOT NULL DEFAULT 0,
    `block_search` TINYINT(4) NOT NULL DEFAULT 0,
    `casino` TINYINT(4) NOT NULL DEFAULT 0,
    `cacheID` CHAR(36) DEFAULT NULL,
    `TerrainPBR1` VARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
    `TerrainPBR2` VARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
    `TerrainPBR3` VARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
    `TerrainPBR4` VARCHAR(36) NOT NULL DEFAULT '00000000-0000-0000-0000-000000000000',
    KEY `regionsettings_regionuuid` (`regionUUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- RegionStore: Baked Terrain
CREATE TABLE `bakedterrain` (
    `RegionUUID` VARCHAR(255) DEFAULT NULL,
    `Revision` INT DEFAULT NULL,
    `Heightfield` LONGBLOB,
    PRIMARY KEY (`RegionUUID`, `Revision`),
    KEY `bakedterrain_regionuuid` (`RegionUUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- RegionStore: Windlight
CREATE TABLE `regionwindlight` (
    `region_id` VARCHAR(36) NOT NULL DEFAULT '000000-0000-0000-0000-000000000000',
    `water_color_r` FLOAT(9,6) NOT NULL DEFAULT 4.0,
    `water_color_g` FLOAT(9,6) NOT NULL DEFAULT 38.0,
    `water_color_b` FLOAT(9,6) NOT NULL DEFAULT 64.0,
    `water_color_i` FLOAT(9,6) NOT NULL DEFAULT 1.0,
    `water_fog_density_exponent` FLOAT(9,6) NOT NULL DEFAULT 4.0,
    `underwater_fog_modifier` FLOAT(9,6) NOT NULL DEFAULT 0.25,
    `reflection_wavelet_scale_1` FLOAT(9,6) NOT NULL DEFAULT 2.0,
    `reflection_wavelet_scale_2` FLOAT(9,6) NOT NULL DEFAULT 2.0,
    `reflection_wavelet_scale_3` FLOAT(9,6) NOT NULL DEFAULT 2.0,
    `fresnel_scale` FLOAT(9,6) NOT NULL DEFAULT 0.40,
    `fresnel_offset` FLOAT(9,6) NOT NULL DEFAULT 0.50,
    `refract_scale_above` FLOAT(9,6) NOT NULL DEFAULT 0.03,
    `refract_scale_below` FLOAT(9,6) NOT NULL DEFAULT 0.20,
    `blur_multiplier` FLOAT(9,6) NOT NULL DEFAULT 0.040,
    `big_wave_direction_x` FLOAT(9,6) NOT NULL DEFAULT 1.05,
    `big_wave_direction_y` FLOAT(9,6) NOT NULL DEFAULT -0.42,
    `little_wave_direction_x` FLOAT(9,6) NOT NULL DEFAULT 1.11,
    `little_wave_direction_y` FLOAT(9,6) NOT NULL DEFAULT -1.16,
    `normal_map_texture` VARCHAR(36) NOT NULL DEFAULT '822ded49-9a6c-f61c-cb89-6df54f42cdf4',
    `horizon_r` FLOAT(9,6) NOT NULL DEFAULT 0.25,
    `horizon_g` FLOAT(9,6) NOT NULL DEFAULT 0.25,
    `horizon_b` FLOAT(9,6) NOT NULL DEFAULT 0.32,
    `horizon_i` FLOAT(9,6) NOT NULL DEFAULT 0.32,
    `haze_horizon` FLOAT(9,6) NOT NULL DEFAULT 0.19,
    `blue_density_r` FLOAT(9,6) NOT NULL DEFAULT 0.12,
    `blue_density_g` FLOAT(9,6) NOT NULL DEFAULT 0.22,
    `blue_density_b` FLOAT(9,6) NOT NULL DEFAULT 0.38,
    `blue_density_i` FLOAT(9,6) NOT NULL DEFAULT 0.38,
    `haze_density` FLOAT(9,6) NOT NULL DEFAULT 0.70,
    `density_multiplier` FLOAT(9,6) NOT NULL DEFAULT 0.18,
    `distance_multiplier` FLOAT(9,6) NOT NULL DEFAULT 0.8,
    `max_altitude` INT NOT NULL DEFAULT 1605,
    `sun_moon_color_r` FLOAT(9,6) NOT NULL DEFAULT 0.24,
    `sun_moon_color_g` FLOAT(9,6) NOT NULL DEFAULT 0.26,
    `sun_moon_color_b` FLOAT(9,6) NOT NULL DEFAULT 0.30,
    `sun_moon_color_i` FLOAT(9,6) NOT NULL DEFAULT 0.30,
    `sun_moon_position` FLOAT(9,6) NOT NULL DEFAULT 0.317,
    `ambient_r` FLOAT(9,6) NOT NULL DEFAULT 0.35,
    `ambient_g` FLOAT(9,6) NOT NULL DEFAULT 0.35,
    `ambient_b` FLOAT(9,6) NOT NULL DEFAULT 0.24,
    `ambient_i` FLOAT(9,6) NOT NULL DEFAULT 0.24,
    `east_angle` FLOAT(9,6) NOT NULL DEFAULT 0.0,
    `sun_glow_focus` FLOAT(9,6) NOT NULL DEFAULT 0.10,
    `sun_glow_size` FLOAT(9,6) NOT NULL DEFAULT 1.75,
    `scene_gamma` FLOAT(9,6) NOT NULL DEFAULT 1.0,
    `star_brightness` FLOAT(9,6) NOT NULL DEFAULT 0.0,
    `cloud_color_r` FLOAT(9,6) NOT NULL DEFAULT 0.41,
    `cloud_color_g` FLOAT(9,6) NOT NULL DEFAULT 0.41,
    `cloud_color_b` FLOAT(9,6) NOT NULL DEFAULT 0.41,
    `cloud_color_i` FLOAT(9,6) NOT NULL DEFAULT 0.41,
    `cloud_x` FLOAT(9,6) NOT NULL DEFAULT 1.0,
    `cloud_y` FLOAT(9,6) NOT NULL DEFAULT 0.53,
    `cloud_density` FLOAT(9,6) NOT NULL DEFAULT 1.0,
    `cloud_coverage` FLOAT(9,6) NOT NULL DEFAULT 0.27,
    `cloud_scale` FLOAT(9,6) NOT NULL DEFAULT 0.42,
    `cloud_detail_x` FLOAT(9,6) NOT NULL DEFAULT 1.0,
    `cloud_detail_y` FLOAT(9,6) NOT NULL DEFAULT 0.53,
    `cloud_detail_density` FLOAT(9,6) NOT NULL DEFAULT 0.12,
    `cloud_scroll_x` FLOAT(9,6) NOT NULL DEFAULT 0.20,
    `cloud_scroll_x_lock` TINYINT(4) NOT NULL DEFAULT 0,
    `cloud_scroll_y` FLOAT(9,6) NOT NULL DEFAULT 0.01,
    `cloud_scroll_y_lock` TINYINT(4) NOT NULL DEFAULT 0,
    `draw_classic_clouds` TINYINT(4) NOT NULL DEFAULT 1,
    PRIMARY KEY (`region_id`),
    KEY `regionwindlight_region_id` (`region_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- RegionStore: Environment
CREATE TABLE `regionenvironment` (
    `region_id` VARCHAR(36) NOT NULL DEFAULT '000000-0000-0000-0000-000000000000',
    `llsd_settings` MEDIUMTEXT,
    PRIMARY KEY (`region_id`),
    KEY `regionenvironment_region_id` (`region_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- RegionStore: Prim Shapes
CREATE TABLE `primshapes` (
    `UUID` CHAR(36) NOT NULL PRIMARY KEY,
    `Shape` INT DEFAULT NULL,
    `ScaleX` DOUBLE DEFAULT NULL,
    `ScaleY` DOUBLE DEFAULT NULL,
    `ScaleZ` DOUBLE DEFAULT NULL,
    `PCode` INT DEFAULT NULL,
    `PathBegin` INT DEFAULT NULL,
    `PathEnd` INT DEFAULT NULL,
    `PathScaleX` INT DEFAULT NULL,
    `PathScaleY` INT DEFAULT NULL,
    `PathShearX` INT DEFAULT NULL,
    `PathShearY` INT DEFAULT NULL,
    `PathSkew` INT DEFAULT NULL,
    `PathCurve` INT DEFAULT NULL,
    `PathRadiusOffset` INT DEFAULT NULL,
    `PathRevolutions` INT DEFAULT NULL,
    `PathTaperX` INT DEFAULT NULL,
    `PathTaperY` INT DEFAULT NULL,
    `PathTwist` INT DEFAULT NULL,
    `PathTwistBegin` INT DEFAULT NULL,
    `ProfileBegin` INT DEFAULT NULL,
    `ProfileEnd` INT DEFAULT NULL,
    `ProfileCurve` INT DEFAULT NULL,
    `ProfileHollow` INT DEFAULT NULL,
    `Texture` LONGBLOB DEFAULT NULL,
    `ExtraParams` BLOB DEFAULT NULL,
    `State` TINYINT DEFAULT NULL,
    `Media` TEXT DEFAULT NULL,
    `MatOvrd` BLOB DEFAULT NULL,
    KEY `primshapes_uuid` (`UUID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;