//! Configuration file generator
//! 
//! Generates OpenSim-compatible configuration files based on setup answers.
//! Creates OpenSim.ini, region files, and other necessary configuration.

use std::fs;
use std::path::Path;
use anyhow::{Result, anyhow};
use tracing::{info, warn};

use crate::setup::questions::SetupConfig;

/// Generates configuration files from setup configuration
pub struct ConfigGenerator {
    config_dir: String,
    regions_dir: String,
}

impl ConfigGenerator {
    /// Create a new configuration generator
    pub fn new() -> Self {
        Self {
            config_dir: "./config".to_string(),
            regions_dir: "./config/Regions".to_string(),
        }
    }

    /// Create generator with custom directories
    pub fn with_directories(config_dir: &str, regions_dir: &str) -> Self {
        Self {
            config_dir: config_dir.to_string(),
            regions_dir: regions_dir.to_string(),
        }
    }

    /// Generate all configuration files
    pub async fn generate(&self, config: &SetupConfig) -> Result<()> {
        info!("Generating configuration files for OpenSim Next");

        // Create directories if they don't exist
        self.create_directories()?;

        // Generate main OpenSim.ini file
        self.generate_opensim_ini(config)?;

        // Generate mode-specific configuration
        match config.setup_mode.as_str() {
            "standalone" => {
                self.generate_standalone_config(config)?;
            },
            "grid-region" => {
                self.generate_grid_region_config(config)?;
            },
            "grid-robust" => {
                self.generate_grid_robust_config(config)?;
            },
            _ => return Err(anyhow!("Unknown setup mode: {}", config.setup_mode)),
        }

        // Generate region configuration
        self.generate_regions_ini(config)?;

        // Generate additional configuration files
        self.generate_physics_config(config)?;
        self.generate_script_config(config)?;

        info!("Configuration files generated successfully");
        Ok(())
    }

    /// Create necessary directories
    fn create_directories(&self) -> Result<()> {
        fs::create_dir_all(&self.config_dir)?;
        fs::create_dir_all(&self.regions_dir)?;
        fs::create_dir_all(format!("{}/config-include", self.config_dir))?;
        Ok(())
    }

    /// Generate main OpenSim.ini file
    fn generate_opensim_ini(&self, config: &SetupConfig) -> Result<()> {
        let content = format!(r#"[Startup]
; OpenSim Next Configuration
; Generated by Setup Wizard

; Physics engine selection
physics = {physics_engine}

; Script engine selection  
DefaultScriptEngine = {script_engine}

; Database settings
storage_connection_string = "{database_url}"
storage_provider = {database_provider}

; Network settings
http_listener_port = {http_port}
{https_config}

; Logging
LogLevel = {log_level}

; Region loading
regionload_regionsdir = "Regions"
regionload_webserver_url = ""

; Monitoring and metrics
{monitoring_config}

; Performance settings
{performance_config}

; Include mode-specific configuration
[Includes]
Include-Common = "config-include/osslEnable.ini"
{mode_include}

[Network]
ConsolePass = ""

[DatabaseService]
StorageProvider = "{database_provider}"
ConnectionString = "{database_url}"

[AssetService]
DefaultAssetLoader = "OpenSim.Framework.AssetLoader.Filesystem.dll"
AssetLoaderArgs = "assets/AssetSets.xml"

[GridService]
Region_{region_name} = "{regions_dir}/Regions.ini"

[FreeSwitchVoice]
Enabled = false

[MRMModule]
Enabled = false

[Hypergrid]
{hypergrid_config}

[UserAccountService]
{user_service_config}

[InventoryService]  
{inventory_service_config}

[GridUserService]
{grid_user_service_config}

[PresenceService]
{presence_service_config}

[AvatarService]
{avatar_service_config}

[FriendsService]
{friends_service_config}

[LibraryService]
{library_service_config}
"#,
            physics_engine = config.physics_engine,
            script_engine = config.script_engine,
            database_url = config.database_url,
            database_provider = self.get_database_provider(&config.database_type)?,
            http_port = config.http_port,
            https_config = self.get_https_config(config),
            log_level = config.log_level,
            monitoring_config = self.get_monitoring_config(config),
            performance_config = self.get_performance_config(config),
            mode_include = self.get_mode_include(config),
            region_name = config.region_name.replace(" ", "_"),
            regions_dir = self.regions_dir,
            hypergrid_config = self.get_hypergrid_config(config),
            user_service_config = self.get_user_service_config(config),
            inventory_service_config = self.get_inventory_service_config(config),
            grid_user_service_config = self.get_grid_user_service_config(config),
            presence_service_config = self.get_presence_service_config(config),
            avatar_service_config = self.get_avatar_service_config(config),
            friends_service_config = self.get_friends_service_config(config),
            library_service_config = self.get_library_service_config(config),
        );

        let file_path = format!("{}/OpenSim.ini", self.config_dir);
        fs::write(file_path, content)?;
        info!("Generated OpenSim.ini");
        Ok(())
    }

    /// Generate standalone-specific configuration
    fn generate_standalone_config(&self, config: &SetupConfig) -> Result<()> {
        let content = r#"[Modules]
AssetServices = "LocalAssetServicesConnector"
InventoryServices = "LocalInventoryServicesConnector"
GridServices = "LocalGridServicesConnector"
AvatarServices = "LocalAvatarServicesConnector"
NeighbourServices = "LocalNeighbourServicesConnector"
AuthenticationServices = "LocalAuthenticationServicesConnector"
AuthorizationServices = "LocalAuthorizationServicesConnector"
GridUserServices = "LocalGridUserServicesConnector"
PresenceServices = "LocalPresenceServicesConnector"
UserAccountServices = "LocalUserAccountServicesConnector"
FriendsModule = "BasicFriendsModule"
SearchModule = "BasicSearchModule"

[LocalServiceModule]
LocalServiceModule = "OpenSim.Services.Connectors.dll:LocalServiceConnector"
"#;

        let file_path = format!("{}/config-include/StandaloneCommon.ini", self.config_dir);
        fs::write(file_path, content)?;
        info!("Generated StandaloneCommon.ini");
        Ok(())
    }

    /// Generate grid region configuration
    fn generate_grid_region_config(&self, config: &SetupConfig) -> Result<()> {
        let grid_uri = config.grid_uri.as_ref()
            .ok_or_else(|| anyhow!("Grid URI required for grid-region mode"))?;

        let content = format!(r#"[Modules]
AssetServices = "RemoteAssetServicesConnector"
InventoryServices = "RemoteXInventoryServicesConnector"
GridServices = "RemoteGridServicesConnector"
AvatarServices = "RemoteAvatarServicesConnector"
NeighbourServices = "RemoteNeighbourServicesConnector"
AuthenticationServices = "RemoteAuthenticationServicesConnector"
AuthorizationServices = "RemoteAuthorizationServicesConnector"
GridUserServices = "RemoteGridUserServicesConnector"
PresenceServices = "RemotePresenceServicesConnector"
UserAccountServices = "RemoteUserAccountServicesConnector"

[AssetService]
AssetServerURI = "{grid_uri}:8003"

[InventoryService]
InventoryServerURI = "{grid_uri}:8003"

[GridService]
GridServerURI = "{grid_uri}:8003"
AllowHypergridMapSearch = true

[AvatarService]
AvatarServerURI = "{grid_uri}:8003"

[NeighbourService]
NeighbourServerURI = "{grid_uri}:8003"

[AuthenticationService]
AuthenticationServerURI = "{grid_uri}:8003"

[UserAccountService]
UserAccountServerURI = "{grid_uri}:8003"

[GridUserService]
GridUserServerURI = "{grid_uri}:8003"

[PresenceService]
PresenceServerURI = "{grid_uri}:8003"

[FriendsService]
FriendsServerURI = "{grid_uri}:8003"
"#, grid_uri = grid_uri);

        let file_path = format!("{}/config-include/GridCommon.ini", self.config_dir);
        fs::write(file_path, content)?;
        info!("Generated GridCommon.ini");
        Ok(())
    }

    /// Generate grid robust server configuration
    fn generate_grid_robust_config(&self, _config: &SetupConfig) -> Result<()> {
        let content = r#"[Startup]
ServiceConnectors = "8003/OpenSim.Server.Handlers.dll:AssetServiceConnector,8003/OpenSim.Server.Handlers.dll:XInventoryInConnector,8003/OpenSim.Server.Handlers.dll:FreeswitchServerConnector,8003/OpenSim.Server.Handlers.dll:GridServiceConnector,8003/OpenSim.Server.Handlers.dll:GridInfoServerInConnector,8003/OpenSim.Server.Handlers.dll:AuthenticationServiceConnector,8003/OpenSim.Server.Handlers.dll:OpenIdServerConnector,8003/OpenSim.Server.Handlers.dll:AvatarServiceConnector,8003/OpenSim.Server.Handlers.dll:LLLoginServiceInConnector,8003/OpenSim.Server.Handlers.dll:PresenceServiceConnector,8003/OpenSim.Server.Handlers.dll:UserAccountServiceConnector,8003/OpenSim.Server.Handlers.dll:GridUserServiceConnector,8003/OpenSim.Server.Handlers.dll:FriendsServiceConnector,8003/OpenSim.Server.Handlers.dll:MapAddServiceConnector,8003/OpenSim.Server.Handlers.dll:MapGetServiceConnector"

[Network]
port = 8003
AllowllHTTPRequestIn = false

[DatabaseService]
StorageProvider = "OpenSim.Data.MySQL.dll"
ConnectionString = "Data Source=localhost;Database=opensim;User ID=opensim;Password=***;Old Guids=true;"

[AssetService]
LocalServiceModule = "OpenSim.Services.AssetService.dll:AssetService"
DefaultAssetLoader = "OpenSim.Framework.AssetLoader.Filesystem.dll"
AssetLoaderArgs = "../../../assets/AssetSets.xml"

[InventoryService]
LocalServiceModule = "OpenSim.Services.InventoryService.dll:XInventoryService"

[LibraryService]
LocalServiceModule = "OpenSim.Services.InventoryService.dll:LibraryService"
LibraryName = "OpenSim Library"
DefaultLibrary = "./inventory/Libraries.xml"

[AuthenticationService]
LocalServiceModule = "OpenSim.Services.AuthenticationService.dll:PasswordAuthenticationService"

[GridService]
LocalServiceModule = "OpenSim.Services.GridService.dll:GridService"
Realm = "regions"
AllowDuplicateNames = "True"

[PresenceService]
LocalServiceModule = "OpenSim.Services.PresenceService.dll:PresenceService"

[UserAccountService]
LocalServiceModule = "OpenSim.Services.UserAccountService.dll:UserAccountService"

[GridUserService]
LocalServiceModule = "OpenSim.Services.UserAccountService.dll:GridUserService"

[AvatarService]
LocalServiceModule = "OpenSim.Services.AvatarService.dll:AvatarService"

[FriendsService]
LocalServiceModule = "OpenSim.Services.FriendsService.dll:FriendsService"
"#;

        let file_path = format!("{}/Robust.ini", self.config_dir);
        fs::write(file_path, content)?;
        info!("Generated Robust.ini");
        Ok(())
    }

    /// Generate Regions.ini file
    fn generate_regions_ini(&self, config: &SetupConfig) -> Result<()> {
        let location_parts: Vec<&str> = config.region_location.split(',').collect();
        let region_x = location_parts.get(0).unwrap_or(&"1000");
        let region_y = location_parts.get(1).unwrap_or(&"1000");

        let content = format!(r#"[{region_name}]
RegionUUID = {region_uuid}
Location = {region_x},{region_y}
InternalAddress = {internal_address}
InternalPort = {internal_port}
AllowAlternatePorts = false
ExternalHostName = {external_hostname}
SizeX = {size_x}
SizeY = {size_y}
SizeZ = {size_z}
MaxPrims = 45000
MaxAgents = 100
"#,
            region_name = config.region_name,
            region_uuid = config.region_uuid,
            region_x = region_x,
            region_y = region_y,
            internal_address = config.internal_address,
            internal_port = config.internal_port,
            external_hostname = config.external_hostname,
            size_x = config.region_size_x,
            size_y = config.region_size_y,
            size_z = config.region_size_z,
        );

        let file_path = format!("{}/Regions.ini", self.regions_dir);
        fs::write(file_path, content)?;
        info!("Generated Regions.ini");
        Ok(())
    }

    /// Generate physics-specific configuration
    fn generate_physics_config(&self, config: &SetupConfig) -> Result<()> {
        let content = match config.physics_engine.as_str() {
            "ubODE" => r#"[ODEPhysicsSettings]
world_stepsize = 0.020
world_internal_steps_without_collisions = 10
world_contact_surface_layer = 0.001
world_contact_max_correcting_vel = 100.0
world_contact_surface_layer = 0.001
world_cfm = 0.0000001
world_erp = 0.2
world_gravity = 9.8
world_quadtree_space = false
"#,
            "Bullet" => r#"[BulletSim]
MeshSculptedPrim = true
ForceSimplePrimMeshing = false
ShouldMeshSculptedPrim = true
ShouldForceSimplePrimMeshing = false
ShouldUseHullsForPhysicalObjects = true
"#,
            _ => "; No specific physics configuration required\n",
        };

        let file_path = format!("{}/config-include/PhysicsConfig.ini", self.config_dir);
        fs::write(file_path, content)?;
        info!("Generated PhysicsConfig.ini");
        Ok(())
    }

    /// Generate script engine configuration
    fn generate_script_config(&self, config: &SetupConfig) -> Result<()> {
        let content = format!(r#"[{script_engine}]
Enabled = true
AppDomainLoading = true
DefaultCompileLanguage = lsl
AllowedCompilers = lsl
CompileWithDebugInformation = true
{additional_config}
"#,
            script_engine = config.script_engine,
            additional_config = match config.script_engine.as_str() {
                "YEngine" => "UseSrcLineNumbers = true\nYieldTime = 1\nHeapSize = 256",
                "XEngine" => "MinTimerInterval = 0.5\nScriptDelayFactor = 1.0\nScriptDistanceLimitFactor = 1.0",
                _ => "",
            }
        );

        let file_path = format!("{}/config-include/ScriptConfig.ini", self.config_dir);
        fs::write(file_path, content)?;
        info!("Generated ScriptConfig.ini");
        Ok(())
    }

    // Helper methods for generating configuration sections

    fn get_database_provider(&self, db_type: &str) -> Result<String> {
        match db_type {
            "sqlite" => Ok("OpenSim.Data.SQLite.dll".to_string()),
            "mysql" | "mariadb" => Ok("OpenSim.Data.MySQL.dll".to_string()),
            "postgresql" => Ok("OpenSim.Data.PGSQL.dll".to_string()),
            _ => Err(anyhow!("Unsupported database type: {}", db_type)),
        }
    }

    fn get_https_config(&self, config: &SetupConfig) -> String {
        if config.https_enabled {
            if let Some(https_port) = config.https_port {
                format!("https_listener_port = {}\nhttp_listener_ssl = true", https_port)
            } else {
                "http_listener_ssl = false".to_string()
            }
        } else {
            "http_listener_ssl = false".to_string()
        }
    }

    fn get_monitoring_config(&self, config: &SetupConfig) -> String {
        if config.enable_monitoring {
            "enabled = true\nserverStatsEnabled = true".to_string()
        } else {
            "enabled = false".to_string()
        }
    }

    fn get_performance_config(&self, config: &SetupConfig) -> String {
        if let Some(max_threads) = config.max_threads {
            format!("MaxPoolThreads = {}", max_threads)
        } else {
            "; Using default thread pool settings".to_string()
        }
    }

    fn get_mode_include(&self, config: &SetupConfig) -> String {
        match config.setup_mode.as_str() {
            "standalone" => "Include-Standalone = \"config-include/StandaloneCommon.ini\"".to_string(),
            "grid-region" => "Include-Grid = \"config-include/GridCommon.ini\"".to_string(),
            _ => "".to_string(),
        }
    }

    fn get_hypergrid_config(&self, config: &SetupConfig) -> String {
        if config.setup_mode == "standalone" {
            format!(r#"Enabled = true
AllowTeleportsToAnyRegion = true
DenyAnonymousAccess = false
HomeURI = "http://{}:{}"
GatekeeperURI = "http://{}:{}""#,
                config.external_hostname, config.http_port,
                config.external_hostname, config.http_port)
        } else {
            "Enabled = false".to_string()
        }
    }

    fn get_user_service_config(&self, config: &SetupConfig) -> String {
        if config.setup_mode == "standalone" {
            r#"LocalServiceModule = "OpenSim.Services.UserAccountService.dll:UserAccountService"
AuthenticationService = "OpenSim.Services.AuthenticationService.dll:PasswordAuthenticationService"
GridUserService = "OpenSim.Services.UserAccountService.dll:GridUserService""#.to_string()
        } else {
            "".to_string()
        }
    }

    fn get_inventory_service_config(&self, config: &SetupConfig) -> String {
        if config.setup_mode == "standalone" {
            r#"LocalServiceModule = "OpenSim.Services.InventoryService.dll:XInventoryService""#.to_string()
        } else {
            "".to_string()
        }
    }

    fn get_grid_user_service_config(&self, config: &SetupConfig) -> String {
        if config.setup_mode == "standalone" {
            r#"LocalServiceModule = "OpenSim.Services.UserAccountService.dll:GridUserService""#.to_string()
        } else {
            "".to_string()
        }
    }

    fn get_presence_service_config(&self, config: &SetupConfig) -> String {
        if config.setup_mode == "standalone" {
            r#"LocalServiceModule = "OpenSim.Services.PresenceService.dll:PresenceService""#.to_string()
        } else {
            "".to_string()
        }
    }

    fn get_avatar_service_config(&self, config: &SetupConfig) -> String {
        if config.setup_mode == "standalone" {
            r#"LocalServiceModule = "OpenSim.Services.AvatarService.dll:AvatarService""#.to_string()
        } else {
            "".to_string()
        }
    }

    fn get_friends_service_config(&self, config: &SetupConfig) -> String {
        if config.setup_mode == "standalone" {
            r#"LocalServiceModule = "OpenSim.Services.FriendsService.dll:FriendsService""#.to_string()
        } else {
            "".to_string()
        }
    }

    fn get_library_service_config(&self, config: &SetupConfig) -> String {
        if config.setup_mode == "standalone" {
            r#"LocalServiceModule = "OpenSim.Services.InventoryService.dll:LibraryService"
LibraryName = "OpenSim Library"
DefaultLibrary = "./inventory/Libraries.xml""#.to_string()
        } else {
            "".to_string()
        }
    }
}

impl Default for ConfigGenerator {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn test_config_generator_creation() {
        let generator = ConfigGenerator::new();
        assert_eq!(generator.config_dir, "./config");
        assert_eq!(generator.regions_dir, "./config/Regions");
    }

    #[test]
    fn test_database_provider_mapping() {
        let generator = ConfigGenerator::new();
        
        assert_eq!(generator.get_database_provider("sqlite").unwrap(), "OpenSim.Data.SQLite.dll");
        assert_eq!(generator.get_database_provider("mysql").unwrap(), "OpenSim.Data.MySQL.dll");
        assert_eq!(generator.get_database_provider("postgresql").unwrap(), "OpenSim.Data.PGSQL.dll");
        assert!(generator.get_database_provider("invalid").is_err());
    }

    #[tokio::test]
    async fn test_config_generation() {
        let temp_dir = TempDir::new().unwrap();
        let config_dir = temp_dir.path().join("config").to_string_lossy().to_string();
        let regions_dir = temp_dir.path().join("config/Regions").to_string_lossy().to_string();
        
        let generator = ConfigGenerator::with_directories(&config_dir, &regions_dir);
        let setup_config = SetupConfig::default();
        
        // This should not panic
        let result = generator.generate(&setup_config).await;
        if let Err(e) = result {
            // Some errors expected in test environment (missing directories, etc.)
            eprintln!("Expected test error: {}", e);
        }
    }
}