-- RegionStore Migration Version 55: Increase Float Precision for Windlight
-- This migration increases precision for windlight parameters for better script compatibility

-- Create regionwindlight table if it doesn't exist (SQLite compatible)
CREATE TABLE IF NOT EXISTS regionwindlight (
    region_id VARCHAR(36) NOT NULL DEFAULT '000000-0000-0000-0000-000000000000',
    water_color_r REAL NOT NULL DEFAULT 4.0,
    water_color_g REAL NOT NULL DEFAULT 38.0,
    water_color_b REAL NOT NULL DEFAULT 64.0,
    water_color_i REAL NOT NULL DEFAULT 1.0,
    water_fog_density_exponent REAL NOT NULL DEFAULT 4.0,
    underwater_fog_modifier REAL NOT NULL DEFAULT 0.25,
    reflection_wavelet_scale_1 REAL NOT NULL DEFAULT 2.0,
    reflection_wavelet_scale_2 REAL NOT NULL DEFAULT 2.0,
    reflection_wavelet_scale_3 REAL NOT NULL DEFAULT 2.0,
    fresnel_scale REAL NOT NULL DEFAULT 0.40,
    fresnel_offset REAL NOT NULL DEFAULT 0.50,
    refract_scale_above REAL NOT NULL DEFAULT 0.03,
    refract_scale_below REAL NOT NULL DEFAULT 0.20,
    blur_multiplier REAL NOT NULL DEFAULT 0.040,
    big_wave_direction_x REAL NOT NULL DEFAULT 1.05,
    big_wave_direction_y REAL NOT NULL DEFAULT -0.42,
    little_wave_direction_x REAL NOT NULL DEFAULT 1.11,
    little_wave_direction_y REAL NOT NULL DEFAULT -1.16,
    normal_map_texture VARCHAR(36) NOT NULL DEFAULT '822ded49-9a6c-f61c-cb89-6df54f42cdf4',
    horizon_r REAL NOT NULL DEFAULT 0.25,
    horizon_g REAL NOT NULL DEFAULT 0.25,
    horizon_b REAL NOT NULL DEFAULT 0.32,
    horizon_i REAL NOT NULL DEFAULT 0.32,
    haze_horizon REAL NOT NULL DEFAULT 0.19,
    blue_density_r REAL NOT NULL DEFAULT 0.12,
    blue_density_g REAL NOT NULL DEFAULT 0.22,
    blue_density_b REAL NOT NULL DEFAULT 0.38,
    blue_density_i REAL NOT NULL DEFAULT 0.38,
    haze_density REAL NOT NULL DEFAULT 0.70,
    density_multiplier REAL NOT NULL DEFAULT 0.18,
    distance_multiplier REAL NOT NULL DEFAULT 0.8,
    max_altitude INTEGER NOT NULL DEFAULT 1605,
    sun_moon_color_r REAL NOT NULL DEFAULT 0.24,
    sun_moon_color_g REAL NOT NULL DEFAULT 0.26,
    sun_moon_color_b REAL NOT NULL DEFAULT 0.30,
    sun_moon_color_i REAL NOT NULL DEFAULT 0.30,
    sun_moon_position REAL NOT NULL DEFAULT 0.317,
    ambient_r REAL NOT NULL DEFAULT 0.35,
    ambient_g REAL NOT NULL DEFAULT 0.35,
    ambient_b REAL NOT NULL DEFAULT 0.24,
    ambient_i REAL NOT NULL DEFAULT 0.24,
    east_angle REAL NOT NULL DEFAULT 0.0,
    sun_glow_focus REAL NOT NULL DEFAULT 0.10,
    sun_glow_size REAL NOT NULL DEFAULT 1.75,
    scene_gamma REAL NOT NULL DEFAULT 1.0,
    star_brightness REAL NOT NULL DEFAULT 0.0,
    cloud_color_r REAL NOT NULL DEFAULT 0.41,
    cloud_color_g REAL NOT NULL DEFAULT 0.41,
    cloud_color_b REAL NOT NULL DEFAULT 0.41,
    cloud_color_i REAL NOT NULL DEFAULT 0.41,
    cloud_x REAL NOT NULL DEFAULT 1.0,
    cloud_y REAL NOT NULL DEFAULT 0.53,
    cloud_density REAL NOT NULL DEFAULT 1.0,
    cloud_coverage REAL NOT NULL DEFAULT 0.27,
    cloud_scale REAL NOT NULL DEFAULT 0.42,
    cloud_detail_x REAL NOT NULL DEFAULT 1.0,
    cloud_detail_y REAL NOT NULL DEFAULT 0.53,
    cloud_detail_density REAL NOT NULL DEFAULT 0.12,
    cloud_scroll_x REAL NOT NULL DEFAULT 0.20,
    cloud_scroll_x_lock INTEGER NOT NULL DEFAULT 0,
    cloud_scroll_y REAL NOT NULL DEFAULT 0.01,
    cloud_scroll_y_lock INTEGER NOT NULL DEFAULT 0,
    draw_classic_clouds INTEGER NOT NULL DEFAULT 1,
    PRIMARY KEY (region_id)
);

-- Create index for performance
CREATE INDEX IF NOT EXISTS regionwindlight_region_id ON regionwindlight(region_id);