use super::models::*;
use std::collections::HashMap;

pub struct IniGenerator;

impl IniGenerator {
    pub fn generate_opensim_ini(config: &OpenSimIniConfig) -> String {
        let mut output = String::new();

        output.push_str("; OpenSim.ini - Generated by OpenSim Next Configuration Builder\n");
        output.push_str("; This file was auto-generated. Manual edits may be overwritten.\n\n");

        output.push_str("[Startup]\n");
        output.push_str(&format!("    gridname = \"{}\"\n", config.grid_name));
        output.push_str(&format!(
            "    welcome_message = \"{}\"\n",
            config.welcome_message
        ));
        output.push_str(&format!(
            "    AllowAnonymousLogin = {}\n",
            config.allow_anonymous_login
        ));
        output.push_str(&format!(
            "    physics = {}\n",
            config.physics_engine.to_ini_string()
        ));
        output.push('\n');

        output.push_str("[Network]\n");
        output.push_str(&format!("    http_listener_port = {}\n", config.http_port));
        output.push_str(&format!(
            "    ExternalHostNameForLSL = {}\n",
            config.external_host_name
        ));
        output.push_str(&format!(
            "    http_listener_address = {}\n",
            config.internal_ip
        ));
        output.push('\n');

        output.push_str("[DatabaseService]\n");
        output.push_str(&format!(
            "    StorageProvider = \"OpenSim.Data.{}.dll\"\n",
            config.database_provider.to_ini_string()
        ));
        output.push_str(&format!(
            "    ConnectionString = \"{}\"\n",
            config.connection_string
        ));
        output.push('\n');

        if config.enable_voice {
            output.push_str("[FreeSwitchVoice]\n");
            output.push_str("    Enabled = true\n");
            output.push('\n');
        }

        if config.enable_search {
            output.push_str("[Search]\n");
            output.push_str("    Enabled = true\n");
            output.push_str("    SearchModule = OpenSimSearch\n");
            output.push('\n');
        }

        if config.enable_currency {
            output.push_str("[Economy]\n");
            output.push_str("    Enabled = true\n");
            output.push_str("    EconomyModule = BetaGridLikeMoneyModule\n");
            output.push('\n');
        }

        for (section_name, section_values) in &config.additional_sections {
            output.push_str(&format!("[{}]\n", section_name));
            for (key, value) in section_values {
                output.push_str(&format!("    {} = {}\n", key, value));
            }
            output.push('\n');
        }

        output
    }

    pub fn generate_region_ini(config: &RegionIniConfig) -> String {
        let mut output = String::new();

        output.push_str("; Regions.ini - Generated by OpenSim Next Configuration Builder\n");
        output.push_str("; This file was auto-generated. Manual edits may be overwritten.\n\n");

        output.push_str(&format!("[{}]\n", config.region_name));
        output.push_str(&format!("    RegionUUID = {}\n", config.region_uuid));
        output.push_str(&format!(
            "    Location = {},{}\n",
            config.location_x, config.location_y
        ));
        output.push_str(&format!("    SizeX = {}\n", config.size_x));
        output.push_str(&format!("    SizeY = {}\n", config.size_y));
        output.push_str(&format!("    InternalPort = {}\n", config.internal_port));
        output.push_str(&format!("    MaxAgents = {}\n", config.max_agents));
        output.push_str(&format!("    MaxPrims = {}\n", config.max_prims));
        output.push('\n');

        output.push_str("; Estate Settings\n");
        output.push_str(&format!("    ; EstateName = {}\n", config.estate_name));
        output.push_str(&format!("    ; EstateOwner = {}\n", config.estate_owner));
        output.push('\n');

        output
    }

    pub fn generate_ossl_enable(config: &OsslConfig) -> String {
        let mut output = String::new();

        output.push_str("; osslEnable.ini - Generated by OpenSim Next Configuration Builder\n");
        output.push_str("; OSSL Security Configuration\n\n");

        output.push_str("[OSSL]\n");
        output.push_str(&format!(
            "    OSFunctionThreatLevel = {}\n",
            config.default_threat_level.to_ini_string()
        ));
        output.push('\n');

        output.push_str("    ; Feature Enables\n");
        output.push_str(&format!("    Allow_osNpcCreate = {}\n", config.enable_npc));
        output.push_str(&format!("    Allow_osNpcMoveTo = {}\n", config.enable_npc));
        output.push_str(&format!("    Allow_osNpcRemove = {}\n", config.enable_npc));
        output.push_str(&format!("    Allow_osNpcSay = {}\n", config.enable_npc));
        output.push('\n');

        output.push_str(&format!(
            "    Allow_osTeleportAgent = {}\n",
            config.enable_teleport
        ));
        output.push_str(&format!(
            "    Allow_osTeleportOwner = {}\n",
            config.enable_teleport
        ));
        output.push('\n');

        output.push_str(&format!(
            "    Allow_osSetDynamicTextureURL = {}\n",
            config.enable_dynamic_textures
        ));
        output.push_str(&format!(
            "    Allow_osSetDynamicTextureURLBlend = {}\n",
            config.enable_dynamic_textures
        ));
        output.push_str(&format!(
            "    Allow_osSetDynamicTextureURLBlendFace = {}\n",
            config.enable_dynamic_textures
        ));
        output.push('\n');

        output.push_str(&format!(
            "    Allow_JsonStore = {}\n",
            config.enable_json_store
        ));
        output.push_str(&format!(
            "    Allow_osGetGridCustom = {}\n",
            config.enable_json_store
        ));
        output.push('\n');

        if !config.allowed_functions.is_empty() {
            output.push_str("    ; Explicitly Allowed Functions\n");
            for func in &config.allowed_functions {
                output.push_str(&format!("    Allow_{} = true\n", func));
            }
            output.push('\n');
        }

        if !config.blocked_functions.is_empty() {
            output.push_str("    ; Explicitly Blocked Functions\n");
            for func in &config.blocked_functions {
                output.push_str(&format!("    Allow_{} = false\n", func));
            }
            output.push('\n');
        }

        output
    }

    pub fn generate_standalone_ini() -> String {
        let mut output = String::new();

        output.push_str("; Standalone.ini - Generated by OpenSim Next Configuration Builder\n\n");

        output.push_str("[Startup]\n");
        output.push_str("    Standalone = true\n");
        output.push('\n');

        output.push_str("[ServiceList]\n");
        output.push_str("    AssetServices = \"LocalAssetServicesConnector\"\n");
        output.push_str("    InventoryServices = \"LocalInventoryServicesConnector\"\n");
        output.push_str("    GridServices = \"LocalGridServicesConnector\"\n");
        output.push_str("    AuthenticationServices = \"LocalAuthenticationServicesConnector\"\n");
        output.push_str("    AuthorizationServices = \"LocalAuthorizationServicesConnector\"\n");
        output.push_str("    PresenceServices = \"LocalPresenceServicesConnector\"\n");
        output.push_str("    UserAccountServices = \"LocalUserAccountServicesConnector\"\n");
        output.push_str("    GridUserServices = \"LocalGridUserServicesConnector\"\n");
        output.push_str("    SimulationServices = \"LocalSimulationConnectorModule\"\n");
        output.push_str("    AvatarServices = \"LocalAvatarServicesConnector\"\n");
        output.push_str("    MapImageService = \"MapImageServiceModule\"\n");
        output.push('\n');

        output.push_str("[InventoryService]\n");
        output.push_str(
            "    LocalServiceModule = \"OpenSim.Services.InventoryService.dll:InventoryService\"\n",
        );
        output.push('\n');

        output.push_str("[AssetService]\n");
        output.push_str(
            "    LocalServiceModule = \"OpenSim.Services.AssetService.dll:AssetService\"\n",
        );
        output.push('\n');

        output.push_str("[UserAccountService]\n");
        output.push_str("    LocalServiceModule = \"OpenSim.Services.UserAccountService.dll:UserAccountService\"\n");
        output.push('\n');

        output.push_str("[PresenceService]\n");
        output.push_str(
            "    LocalServiceModule = \"OpenSim.Services.PresenceService.dll:PresenceService\"\n",
        );
        output.push('\n');

        output.push_str("[AvatarService]\n");
        output.push_str(
            "    LocalServiceModule = \"OpenSim.Services.AvatarService.dll:AvatarService\"\n",
        );
        output.push('\n');

        output.push_str("[AuthenticationService]\n");
        output.push_str("    LocalServiceModule = \"OpenSim.Services.AuthenticationService.dll:PasswordAuthenticationService\"\n");
        output.push('\n');

        output
    }

    pub fn generate_grid_common_ini(grid_uri: &str, grid_services: &GridServices) -> String {
        let mut output = String::new();

        output.push_str("; GridCommon.ini - Generated by OpenSim Next Configuration Builder\n\n");

        output.push_str("[ServiceList]\n");
        output.push_str("    AssetServices = \"HGAssetBroker\"\n");
        output.push_str("    InventoryServices = \"HGInventoryBroker\"\n");
        output.push_str("    GridServices = \"RemoteGridServicesConnector\"\n");
        output.push_str("    AuthenticationServices = \"RemoteAuthenticationServicesConnector\"\n");
        output.push_str("    AuthorizationServices = \"LocalAuthorizationServicesConnector\"\n");
        output.push_str("    PresenceServices = \"RemotePresenceServicesConnector\"\n");
        output.push_str("    UserAccountServices = \"RemoteUserAccountServicesConnector\"\n");
        output.push_str("    GridUserServices = \"RemoteGridUserServicesConnector\"\n");
        output.push_str("    SimulationServices = \"RemoteSimulationConnectorModule\"\n");
        output.push_str("    AvatarServices = \"RemoteAvatarServicesConnector\"\n");
        output.push_str("    MapImageService = \"MapImageServiceModule\"\n");
        output.push('\n');

        output.push_str("[AssetService]\n");
        output.push_str(&format!(
            "    AssetServerURI = \"{}\"\n",
            grid_services.asset_server_uri
        ));
        output.push('\n');

        output.push_str("[InventoryService]\n");
        output.push_str(&format!(
            "    InventoryServerURI = \"{}\"\n",
            grid_services.inventory_server_uri
        ));
        output.push('\n');

        output.push_str("[GridService]\n");
        output.push_str(&format!("    GridServerURI = \"{}\"\n", grid_uri));
        output.push('\n');

        output.push_str("[UserAccountService]\n");
        output.push_str(&format!(
            "    UserAccountServerURI = \"{}\"\n",
            grid_services.user_account_server_uri
        ));
        output.push('\n');

        output.push_str("[AuthenticationService]\n");
        output.push_str(&format!(
            "    AuthenticationServerURI = \"{}\"\n",
            grid_services.authentication_server_uri
        ));
        output.push('\n');

        output.push_str("[PresenceService]\n");
        output.push_str(&format!(
            "    PresenceServerURI = \"{}\"\n",
            grid_services.presence_server_uri
        ));
        output.push('\n');

        output.push_str("[AvatarService]\n");
        output.push_str(&format!(
            "    AvatarServerURI = \"{}\"\n",
            grid_services.avatar_server_uri
        ));
        output.push('\n');

        output
    }

    pub fn generate_config_includes(includes: &HashMap<String, String>) -> HashMap<String, String> {
        let mut result = HashMap::new();

        for (filename, content) in includes {
            let formatted = format!(
                "; {} - Generated by OpenSim Next Configuration Builder\n\n{}",
                filename, content
            );
            result.insert(filename.clone(), formatted);
        }

        result
    }

    pub fn generate_docker_compose_override(
        config: &SavedConfiguration,
        instance_name: &str,
    ) -> String {
        let container_config = config
            .container_config
            .as_ref()
            .map(|c| c.clone())
            .unwrap_or_default();

        let mut output = String::new();

        output.push_str("# docker-compose.override.yml\n");
        output.push_str("# Generated by OpenSim Next Configuration Builder\n\n");
        output.push_str("version: '3.8'\n\n");
        output.push_str("services:\n");
        output.push_str(&format!("  {}:\n", instance_name));

        if let Some(image) = &container_config.docker_image {
            output.push_str(&format!("    image: {}\n", image));
        } else {
            output.push_str("    image: opensim-next:latest\n");
        }

        output.push_str("    deploy:\n");
        output.push_str("      resources:\n");
        output.push_str("        limits:\n");
        output.push_str(&format!(
            "          memory: {}M\n",
            container_config.memory_limit_mb
        ));
        output.push_str(&format!(
            "          cpus: '{}'\n",
            container_config.cpu_limit
        ));

        if !container_config.ports.is_empty() {
            output.push_str("    ports:\n");
            for port in &container_config.ports {
                output.push_str(&format!(
                    "      - \"{}:{}/{}\"\n",
                    port.host_port, port.container_port, port.protocol
                ));
            }
        } else {
            output.push_str("    ports:\n");
            output.push_str(&format!(
                "      - \"{}:{}/tcp\"\n",
                config.opensim_ini.http_port, config.opensim_ini.http_port
            ));
            output.push_str(&format!(
                "      - \"{}:{}/udp\"\n",
                config.region_ini.internal_port, config.region_ini.internal_port
            ));
        }

        output.push_str("    volumes:\n");
        output.push_str(&format!("      - ./config/{}:/app/bin:ro\n", instance_name));
        output.push_str(&format!(
            "      - opensim-{}-data:/app/data\n",
            instance_name
        ));

        if !container_config.volumes.is_empty() {
            for volume in &container_config.volumes {
                output.push_str(&format!("      - {}\n", volume));
            }
        }

        if !container_config.env_vars.is_empty() {
            output.push_str("    environment:\n");
            for (key, value) in &container_config.env_vars {
                output.push_str(&format!("      {}: \"{}\"\n", key, value));
            }
        }

        output.push_str("    restart: unless-stopped\n");
        output.push_str("    networks:\n");
        output.push_str("      - opensim-network\n\n");

        output.push_str("volumes:\n");
        output.push_str(&format!("  opensim-{}-data:\n", instance_name));
        output.push_str("    driver: local\n\n");

        output.push_str("networks:\n");
        output.push_str("  opensim-network:\n");
        output.push_str("    external: true\n");

        output
    }

    pub fn generate_kubernetes_configmap(
        config: &SavedConfiguration,
        instance_name: &str,
    ) -> String {
        let namespace = config
            .container_config
            .as_ref()
            .and_then(|c| c.namespace.clone())
            .unwrap_or_else(|| "opensim".to_string());

        let mut output = String::new();

        output.push_str("# ConfigMap for OpenSim instance\n");
        output.push_str("# Generated by OpenSim Next Configuration Builder\n");
        output.push_str("apiVersion: v1\n");
        output.push_str("kind: ConfigMap\n");
        output.push_str("metadata:\n");
        output.push_str(&format!("  name: opensim-{}-config\n", instance_name));
        output.push_str(&format!("  namespace: {}\n", namespace));
        output.push_str("  labels:\n");
        output.push_str("    app: opensim-next\n");
        output.push_str(&format!("    instance: {}\n", instance_name));
        output.push_str("data:\n");

        let opensim_ini = Self::generate_opensim_ini(&config.opensim_ini);
        output.push_str("  OpenSim.ini: |\n");
        for line in opensim_ini.lines() {
            output.push_str(&format!("    {}\n", line));
        }

        let region_ini = Self::generate_region_ini(&config.region_ini);
        output.push_str("  Regions.ini: |\n");
        for line in region_ini.lines() {
            output.push_str(&format!("    {}\n", line));
        }

        let ossl_ini = Self::generate_ossl_enable(&config.ossl_config);
        output.push_str("  osslEnable.ini: |\n");
        for line in ossl_ini.lines() {
            output.push_str(&format!("    {}\n", line));
        }

        output
    }

    pub fn generate_helm_values(config: &SavedConfiguration, instance_name: &str) -> String {
        let container_config = config
            .container_config
            .as_ref()
            .map(|c| c.clone())
            .unwrap_or_default();

        let mut output = String::new();

        output.push_str("# Helm values.yaml override\n");
        output.push_str("# Generated by OpenSim Next Configuration Builder\n\n");

        output.push_str(&format!("instanceName: {}\n\n", instance_name));

        output.push_str("replicaCount: ");
        output.push_str(&format!("{}\n\n", container_config.replicas));

        output.push_str("image:\n");
        if let Some(image) = &container_config.docker_image {
            let parts: Vec<&str> = image.split(':').collect();
            output.push_str(&format!(
                "  repository: {}\n",
                parts.get(0).unwrap_or(&"opensim-next")
            ));
            output.push_str(&format!("  tag: {}\n\n", parts.get(1).unwrap_or(&"latest")));
        } else {
            output.push_str("  repository: opensim-next\n");
            output.push_str("  tag: latest\n\n");
        }

        output.push_str("resources:\n");
        output.push_str("  limits:\n");
        output.push_str(&format!(
            "    memory: {}Mi\n",
            container_config.memory_limit_mb
        ));
        output.push_str(&format!("    cpu: {}\n", container_config.cpu_limit));
        output.push_str("  requests:\n");
        output.push_str(&format!(
            "    memory: {}Mi\n",
            container_config.memory_limit_mb / 2
        ));
        output.push_str(&format!(
            "    cpu: {}\n\n",
            container_config.cpu_limit / 2.0
        ));

        output.push_str("service:\n");
        output.push_str("  type: LoadBalancer\n");
        output.push_str(&format!("  httpPort: {}\n", config.opensim_ini.http_port));
        output.push_str(&format!(
            "  udpPort: {}\n\n",
            config.region_ini.internal_port
        ));

        if container_config.enable_hpa {
            output.push_str("autoscaling:\n");
            output.push_str("  enabled: true\n");
            output.push_str(&format!(
                "  minReplicas: {}\n",
                container_config.min_replicas
            ));
            output.push_str(&format!(
                "  maxReplicas: {}\n",
                container_config.max_replicas
            ));
            output.push_str("  targetCPUUtilizationPercentage: 80\n\n");
        }

        if let Some(ingress_host) = &container_config.ingress_host {
            output.push_str("ingress:\n");
            output.push_str("  enabled: true\n");
            output.push_str("  className: nginx\n");
            output.push_str("  hosts:\n");
            output.push_str(&format!("    - host: {}\n", ingress_host));
            output.push_str("      paths:\n");
            output.push_str("        - path: /\n");
            output.push_str("          pathType: Prefix\n");
            if container_config.enable_tls {
                output.push_str("  tls:\n");
                output.push_str(&format!("    - secretName: {}-tls\n", instance_name));
                output.push_str("      hosts:\n");
                output.push_str(&format!("        - {}\n", ingress_host));
            }
        }

        output
    }
}

#[derive(Debug, Clone)]
pub struct GridServices {
    pub asset_server_uri: String,
    pub inventory_server_uri: String,
    pub user_account_server_uri: String,
    pub authentication_server_uri: String,
    pub presence_server_uri: String,
    pub avatar_server_uri: String,
}

impl Default for GridServices {
    fn default() -> Self {
        Self {
            asset_server_uri: "http://localhost:8003".to_string(),
            inventory_server_uri: "http://localhost:8003".to_string(),
            user_account_server_uri: "http://localhost:8003".to_string(),
            authentication_server_uri: "http://localhost:8003".to_string(),
            presence_server_uri: "http://localhost:8003".to_string(),
            avatar_server_uri: "http://localhost:8003".to_string(),
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_generate_opensim_ini() {
        let config = OpenSimIniConfig::default();
        let ini = IniGenerator::generate_opensim_ini(&config);

        assert!(ini.contains("[Startup]"));
        assert!(ini.contains("[Network]"));
        assert!(ini.contains("[DatabaseService]"));
        assert!(ini.contains("gridname = \"OpenSim Next\""));
    }

    #[test]
    fn test_generate_region_ini() {
        let config = RegionIniConfig::default();
        let ini = IniGenerator::generate_region_ini(&config);

        assert!(ini.contains("[New Region]"));
        assert!(ini.contains("RegionUUID"));
        assert!(ini.contains("Location = 1000,1000"));
    }

    #[test]
    fn test_generate_ossl_enable() {
        let config = OsslConfig::default();
        let ini = IniGenerator::generate_ossl_enable(&config);

        assert!(ini.contains("[OSSL]"));
        assert!(ini.contains("OSFunctionThreatLevel = Low"));
    }
}
