#!/bin/bash
# Quick Start Standalone - Server Startup Script
# Auto-generated by OpenSim Next Setup Wizard

echo "🌟 Starting Your First Virtual World..."
echo "Template: Quick Start Standalone"
echo "Region: MyFirstRegion"
echo ""

# Set working directory
cd "$(dirname "$0")/../configs" || exit 1

# Check if this is first run
if [ ! -f "opensim.db" ]; then
    echo "🔧 First time setup - creating database..."
    echo "⏱️  This may take a moment..."
fi

# Set environment variables
export MONO_THREADS_PER_CPU=2000
export RUST_LOG=info

# Create admin user on first run
if [ ! -f ".admin_created" ]; then
    echo "👤 Creating admin user account..."
    # Admin creation will happen automatically on server start
    touch .admin_created
fi

echo "🚀 Launching OpenSim server..."
echo "💡 Your world will be ready when you see: 'Region MyFirstRegion is now ready'"
echo ""
echo "📍 Connection Details:"
echo "   Grid URI: http://127.0.0.1:8080"
echo "   Region: MyFirstRegion (1000,1000)"
echo "   Admin: NewUser Admin"
echo ""
echo "🌐 Web Dashboard: http://127.0.0.1:8080/admin"
echo ""

# Start OpenSim (adjust path as needed)
if command -v mono >/dev/null 2>&1; then
    # Use Mono if available (Linux/macOS)
    mono ../../../bin/OpenSim.exe
elif [ -f "../../../bin/OpenSim.exe" ]; then
    # Direct execution (Windows with .NET)
    ../../../bin/OpenSim.exe
else
    echo "❌ Error: OpenSim.exe not found!"
    echo "💡 Make sure you're running this from the correct directory"
    exit 1
fi

echo ""
echo "👋 Thanks for using OpenSim Next!"
echo "🎯 Your virtual world has stopped. Run this script again to restart."