//! Go SDK generator for OpenSim client libraries

use super::{
    api_schema::*,
    generator::{LanguageGenerator, GeneratorConfig, GenerationResult, GeneratedFile, GeneratedFileType, PackageInfo, CodeGenUtils, TargetLanguage},
};
use anyhow::Result;
use std::collections::HashMap;

/// Go SDK generator implementation
pub struct GoGenerator;

impl LanguageGenerator for GoGenerator {
    fn language_name(&self) -> &'static str {
        "Go"
    }

    fn file_extension(&self) -> &'static str {
        "go"
    }

    fn generate_sdk(&self, schema: &ApiSchema, config: &GeneratorConfig) -> Result<HashMap<String, String>> {
        let mut files = HashMap::new();

        // Generate main client
        files.insert("client.go".to_string(), self.generate_client(schema, config)?);
        
        // Generate types
        files.insert("types.go".to_string(), self.generate_types(schema)?);
        
        // Generate authentication
        files.insert("auth.go".to_string(), self.generate_auth(schema)?);
        
        // Generate API methods
        for endpoint in &schema.endpoints {
            let category = endpoint.path.split('/').nth(1).unwrap_or("misc");
            let filename = format!("{}.go", to_snake_case(category));
            if !files.contains_key(&filename) {
                files.insert(filename.clone(), self.generate_api_category(schema, category)?);
            }
        }
        
        // Generate examples
        files.insert("examples/main.go".to_string(), self.generate_examples(schema, config)?);
        
        // Generate tests
        files.insert("client_test.go".to_string(), self.generate_tests(schema)?);
        
        // Generate module files
        files.insert("go.mod".to_string(), self.generate_go_mod(config)?);
        files.insert("README.md".to_string(), self.generate_readme(config)?);

        Ok(files)
    }

    fn generate_type_definition(&self, type_def: &TypeDefinition) -> Result<String> {
        match type_def {
            TypeDefinition::Object(obj) => {
                let mut result = format!("// {}\ntype {} struct {{\n", 
                    obj.description.as_deref().unwrap_or(""),
                    to_pascal_case(&obj.name));
                
                for field in &obj.fields {
                    let field_type = self.map_type(&field.field_type);
                    let json_tag = format!("`json:\"{}\"`", field.name);
                    result.push_str(&format!("\t{} {} {}\n", 
                        to_pascal_case(&field.name), field_type, json_tag));
                }
                
                result.push_str("}\n\n");
                Ok(result)
            }
            TypeDefinition::Enum(enum_def) => {
                let mut result = format!("// {}\ntype {} string\n\nconst (\n", 
                    enum_def.description.as_deref().unwrap_or(""),
                    to_pascal_case(&enum_def.name));
                
                for variant in &enum_def.variants {
                    result.push_str(&format!("\t{}{} {} = \"{}\"\n", 
                        to_pascal_case(&enum_def.name),
                        to_pascal_case(&variant.name),
                        to_pascal_case(&enum_def.name),
                        variant.value));
                }
                
                result.push_str(")\n\n");
                Ok(result)
            }
        }
    }
}

impl GoGenerator {
    fn generate_client(&self, schema: &ApiSchema, config: &GeneratorConfig) -> Result<String> {
        Ok(format!(r#"// Package opensim provides a Go client for the OpenSim API
//
// Generated by OpenSim SDK Generator
// Version: {}

package opensim

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// Client represents the OpenSim API client
type Client struct {{
	baseURL    string
	httpClient *http.Client
	auth       *AuthConfig
	apiKey     string
}}

// ClientConfig holds configuration for the client
type ClientConfig struct {{
	BaseURL    string
	APIKey     string
	Timeout    time.Duration
	UserAgent  string
}}

// NewClient creates a new OpenSim API client
func NewClient(config ClientConfig) *Client {{
	if config.Timeout == 0 {{
		config.Timeout = 30 * time.Second
	}}
	
	if config.UserAgent == "" {{
		config.UserAgent = "opensim-go-sdk/{}"
	}}

	return &Client{{
		baseURL: strings.TrimSuffix(config.BaseURL, "/"),
		httpClient: &http.Client{{
			Timeout: config.Timeout,
		}},
		apiKey: config.APIKey,
	}}
}}

// Error represents an API error response
type Error struct {{
	Code    int    `json:"code"`
	Message string `json:"message"`
	Details string `json:"details,omitempty"`
}}

func (e Error) Error() string {{
	return fmt.Sprintf("OpenSim API error %d: %s", e.Code, e.Message)
}}

// Response represents an API response wrapper
type Response[T any] struct {{
	Data    T      `json:"data"`
	Status  string `json:"status"`
	Message string `json:"message,omitempty"`
}}

// makeRequest performs an HTTP request to the API
func (c *Client) makeRequest(ctx context.Context, method, path string, body interface{{}}, result interface{{}}) error {{
	url := c.baseURL + path
	
	var reqBody io.Reader
	if body != nil {{
		jsonData, err := json.Marshal(body)
		if err != nil {{
			return fmt.Errorf("failed to marshal request body: %w", err)
		}}
		reqBody = strings.NewReader(string(jsonData))
	}}
	
	req, err := http.NewRequestWithContext(ctx, method, url, reqBody)
	if err != nil {{
		return fmt.Errorf("failed to create request: %w", err)
	}}
	
	// Set headers
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("User-Agent", "opensim-go-sdk/{}")
	if c.apiKey != "" {{
		req.Header.Set("X-API-Key", c.apiKey)
	}}
	
	resp, err := c.httpClient.Do(req)
	if err != nil {{
		return fmt.Errorf("failed to make request: %w", err)
	}}
	defer resp.Body.Close()
	
	if resp.StatusCode >= 400 {{
		var apiErr Error
		if err := json.NewDecoder(resp.Body).Decode(&apiErr); err != nil {{
			return fmt.Errorf("HTTP %d: failed to decode error response", resp.StatusCode)
		}}
		apiErr.Code = resp.StatusCode
		return apiErr
	}}
	
	if result != nil {{
		if err := json.NewDecoder(resp.Body).Decode(result); err != nil {{
			return fmt.Errorf("failed to decode response: %w", err)
		}}
	}}
	
	return nil
}}

// Ping tests the connection to the API
func (c *Client) Ping(ctx context.Context) error {{
	return c.makeRequest(ctx, "GET", "/api/health", nil, nil)
}}
"#, config.version, config.version, config.version))
    }

    fn generate_types(&self, schema: &ApiSchema) -> Result<String> {
        let mut result = String::from(r#"package opensim

import (
	"time"
)

"#);

        for type_def in &schema.types {
            result.push_str(&self.generate_type_definition(type_def)?);
        }

        Ok(result)
    }

    fn generate_auth(&self, _schema: &ApiSchema) -> Result<String> {
        Ok(r#"package opensim

import (
	"context"
	"fmt"
)

// AuthConfig holds authentication configuration
type AuthConfig struct {
	Username    string `json:"username"`
	Password    string `json:"password"`
	Token       string `json:"token,omitempty"`
	ExpiresAt   int64  `json:"expires_at,omitempty"`
}

// LoginRequest represents a login request
type LoginRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

// LoginResponse represents a login response
type LoginResponse struct {
	Token     string `json:"token"`
	ExpiresAt int64  `json:"expires_at"`
	UserID    string `json:"user_id"`
}

// Login authenticates with the OpenSim API
func (c *Client) Login(ctx context.Context, username, password string) (*LoginResponse, error) {
	req := LoginRequest{
		Username: username,
		Password: password,
	}
	
	var resp Response[LoginResponse]
	err := c.makeRequest(ctx, "POST", "/api/auth/login", req, &resp)
	if err != nil {
		return nil, err
	}
	
	// Store auth config
	c.auth = &AuthConfig{
		Username:  username,
		Token:     resp.Data.Token,
		ExpiresAt: resp.Data.ExpiresAt,
	}
	
	return &resp.Data, nil
}

// Logout logs out from the OpenSim API
func (c *Client) Logout(ctx context.Context) error {
	if c.auth == nil {
		return fmt.Errorf("not logged in")
	}
	
	err := c.makeRequest(ctx, "POST", "/api/auth/logout", nil, nil)
	if err != nil {
		return err
	}
	
	c.auth = nil
	return nil
}

// IsAuthenticated checks if the client is authenticated
func (c *Client) IsAuthenticated() bool {
	return c.auth != nil && c.auth.Token != ""
}
"#.to_string())
    }

    fn generate_api_category(&self, schema: &ApiSchema, category: &str) -> Result<String> {
        let mut result = format!(r#"package opensim

import (
	"context"
	"fmt"
)

"#);

        let endpoints: Vec<_> = schema.endpoints.iter()
            .filter(|e| e.path.starts_with(&format!("/{}", category)))
            .collect();

        for endpoint in endpoints {
            result.push_str(&self.generate_endpoint_method(endpoint)?);
        }

        Ok(result)
    }

    fn generate_endpoint_method(&self, endpoint: &ApiEndpoint) -> Result<String> {
        let method_name = self.generate_method_name(&endpoint.path, &endpoint.method);
        let path_with_params = self.generate_path_with_params(&endpoint.path);
        
        let mut params = Vec::new();
        let mut path_params = Vec::new();
        
        // Add path parameters
        for param in &endpoint.parameters {
            if param.location == ParameterLocation::Path {
                params.push(format!("{} {}", to_camel_case(&param.name), self.map_type(&param.param_type)));
                path_params.push(param.name.clone());
            }
        }
        
        // Add query parameters as a struct
        if endpoint.parameters.iter().any(|p| p.location == ParameterLocation::Query) {
            params.push("opts QueryOptions".to_string());
        }
        
        // Add request body
        if let Some(request_body) = &endpoint.request_body {
            params.push(format!("req {}", self.map_type(&request_body.content_type)));
        }
        
        let params_str = if params.is_empty() {
            "ctx context.Context".to_string()
        } else {
            format!("ctx context.Context, {}", params.join(", "))
        };
        
        let return_type = if let Some(response) = endpoint.responses.get("200") {
            format!("(*{}, error)", self.map_type(&response.content_type))
        } else {
            "error".to_string()
        };

        Ok(format!(r#"// {} {}
func (c *Client) {}({}) {} {{
	path := "{}"
{}
	
	var result {}
	err := c.makeRequest(ctx, "{}", path, {}, &result)
	if err != nil {{
		return {}, err
	}}
	
	return {}, nil
}}

"#, 
            endpoint.method.to_uppercase(),
            endpoint.path,
            method_name,
            params_str,
            return_type,
            path_with_params,
            self.generate_path_replacements(&path_params),
            if let Some(response) = endpoint.responses.get("200") {
                self.map_type(&response.content_type)
            } else {
                "interface{}".to_string()
            },
            endpoint.method.to_uppercase(),
            if endpoint.request_body.is_some() { "req" } else { "nil" },
            if endpoint.responses.get("200").is_some() { "nil" } else { "" },
            if endpoint.responses.get("200").is_some() { "&result" } else { "nil" }
        ))
    }

    fn generate_method_name(&self, path: &str, method: &str) -> String {
        let parts: Vec<&str> = path.split('/').filter(|s| !s.is_empty() && !s.starts_with('{')).collect();
        let name = parts.join("_");
        to_pascal_case(&format!("{}_{}", method, name))
    }

    fn generate_path_with_params(&self, path: &str) -> String {
        path.replace('{', "%s").replace('}', "")
    }

    fn generate_path_replacements(&self, path_params: &[String]) -> String {
        if path_params.is_empty() {
            return String::new();
        }
        
        let replacements: Vec<String> = path_params.iter()
            .map(|p| to_camel_case(p))
            .collect();
        
        format!("\tpath = fmt.Sprintf(path, {})", replacements.join(", "))
    }

    fn generate_examples(&self, _schema: &ApiSchema, config: &GeneratorConfig) -> Result<String> {
        Ok(format!(r#"// Example usage of the OpenSim Go SDK
package main

import (
	"context"
	"fmt"
	"log"
	"time"

	"github.com/{}/{}"
)

func main() {{
	// Create client
	client := opensim.NewClient(opensim.ClientConfig{{
		BaseURL: "https://api.opensim.org",
		APIKey:  "your-api-key",
		Timeout: 30 * time.Second,
	}})

	ctx := context.Background()

	// Test connection
	if err := client.Ping(ctx); err != nil {{
		log.Fatalf("Failed to ping API: %v", err)
	}}
	fmt.Println("Successfully connected to OpenSim API")

	// Login
	loginResp, err := client.Login(ctx, "username", "password")
	if err != nil {{
		log.Fatalf("Failed to login: %v", err)
	}}
	fmt.Printf("Logged in successfully. Token expires at: %d\n", loginResp.ExpiresAt)

	// Example API calls would go here...

	// Logout
	if err := client.Logout(ctx); err != nil {{
		log.Printf("Failed to logout: %v", err)
	}}
}}
"#, 
            config.organization.as_deref().unwrap_or("opensim"),
            config.package_name.as_deref().unwrap_or("opensim-go-sdk"),
            config.package_name.as_deref().unwrap_or("opensim")))
    }

    fn generate_tests(&self, _schema: &ApiSchema) -> Result<String> {
        Ok(r#"package opensim

import (
	"context"
	"testing"
	"time"
)

func TestNewClient(t *testing.T) {
	config := ClientConfig{
		BaseURL: "https://api.example.com",
		APIKey:  "test-key",
		Timeout: 10 * time.Second,
	}
	
	client := NewClient(config)
	
	if client.baseURL != "https://api.example.com" {
		t.Errorf("Expected baseURL to be 'https://api.example.com', got '%s'", client.baseURL)
	}
	
	if client.apiKey != "test-key" {
		t.Errorf("Expected apiKey to be 'test-key', got '%s'", client.apiKey)
	}
}

func TestClientPing(t *testing.T) {
	// This would require a mock server for proper testing
	t.Skip("Requires mock server implementation")
}

func TestAuthentication(t *testing.T) {
	client := NewClient(ClientConfig{
		BaseURL: "https://api.example.com",
		APIKey:  "test-key",
	})
	
	if client.IsAuthenticated() {
		t.Error("Expected client to not be authenticated initially")
	}
}
"#.to_string())
    }

    fn generate_go_mod(&self, config: &GeneratorConfig) -> Result<String> {
        Ok(format!(r#"module github.com/{}/{}

go 1.21

require (
	// No external dependencies - uses only standard library
)
"#, 
            config.organization.as_deref().unwrap_or("opensim"),
            config.package_name.as_deref().unwrap_or("opensim-go-sdk")))
    }

    fn generate_readme(&self, config: &GeneratorConfig) -> Result<String> {
        Ok(format!(r#"# OpenSim Go SDK

Official Go client library for the OpenSim API.

## Installation

```bash
go get github.com/{}/{}
```

## Quick Start

```go
package main

import (
    "context"
    "fmt"
    "log"
    
    "github.com/{}/{}"
)

func main() {{
    client := opensim.NewClient(opensim.ClientConfig{{
        BaseURL: "https://api.opensim.org",
        APIKey:  "your-api-key",
    }})
    
    ctx := context.Background()
    
    // Test connection
    if err := client.Ping(ctx); err != nil {{
        log.Fatal(err)
    }}
    
    fmt.Println("Connected to OpenSim API!")
}}
```

## Features

- **Async/Await Support**: Built with Go's context package
- **Type Safety**: Full type definitions for all API responses
- **Error Handling**: Comprehensive error types with detailed messages
- **Authentication**: Built-in support for API key and token authentication
- **Testing**: Comprehensive test suite with mock server support

## Documentation

Full API documentation is available at [https://docs.opensim.org](https://docs.opensim.org).

## License

{}
"#, 
            config.organization.as_deref().unwrap_or("opensim"),
            config.package_name.as_deref().unwrap_or("opensim-go-sdk"),
            config.organization.as_deref().unwrap_or("opensim"),
            config.package_name.as_deref().unwrap_or("opensim-go-sdk"),
            config.license.as_deref().unwrap_or("MIT")))
    }

    fn map_type(&self, data_type: &DataType) -> String {
        match data_type {
            DataType::String => "string".to_string(),
            DataType::Integer => "int64".to_string(),
            DataType::Number => "float64".to_string(),
            DataType::Boolean => "bool".to_string(),
            DataType::Array(inner) => format!("[]{}", self.map_type(inner)),
            DataType::Object(name) => to_pascal_case(name),
            DataType::Optional(inner) => format!("*{}", self.map_type(inner)),
            DataType::Map(value_type) => format!("map[string]{}", self.map_type(value_type)),
        }
    }
}